spring:
  application:
    name: deterministic-clasifying-svc


  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: deterministic-classifying-svc
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8085